
name: mobile_arquitetura_02
description: Arquitetura em camadas Flutter
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0

flutter:
  uses-material-design: true
